<?php
if(!defined('ok')) { die; }
?>

<div class="big-info clearfix">
			<div class="user_info clearfix">
				<h2>Perfil e informaci&oacute;n de @DrDexter</h2>
			</div><ul style="margin:6px;"><li><label>Nombre</label><strong>No especificado</strong></li><li><label>Fecha de nacimiento</label><strong>No especificado</strong></li><li><label>Pa&iacute;s</label><strong></strong></li><li><label>Email</label><strong>vasquez.boris001@gmail.com</strong></li><li><label>Es usuario desde</label><strong>Hace 1 a&ntilde;o y 1 mes </strong></li><li><label>Estudios</label><strong>No especificado</strong></li><li class="sep"><h4>Vida personal</h4></li><li><label>Le gustar&iacute;a</label><strong>No especificado</strong></li><li><label>Estado civil</label><strong>No especificado</strong></li><li><label>Hijos</label><strong>No especificado</strong></li><li><label>Vive con</label><strong>No especificado</strong></li><li class="sep"><h4>&iquest;C&oacute;mo es?</h4></li><li><label>Mide</label><strong>No especificado</strong></li><li><label>Pesa</label><strong>No especificado</strong></li><li><label>Su pelo es</label><strong>No especificado</strong></li><li><label>Sus ojos son</label><strong>No especificado</strong></li><li><label>Su f&iacute;sico es</label><strong>No especificado</strong></li><li class="sep"><h4>H&aacute;bitos personales</h4></li><li><label>Mantiene una dieta</label><strong>No especificado</strong></li><li><label>Fuma</label><strong>No especificado</strong></li><li><label>Toma alcohol</label><strong>No especificado</strong></li><li class="sep"><h4>Vida profesional</h4></li><li><label>Su profesi&oacute;n</label><strong>No especificado</strong></li><li><label>Trabaja en</label><strong>No especificado</strong></li><li><label>Nivel de ingresos</label><strong>No especificado</strong></li><li><label>Sus inter&eacute;ses profesionales</label><strong>No especificado</strong></li><li><label>Sus habilidades profesionales</label><strong>No especificado</strong></li><li><label>Sector laboral</label><strong>No especificado</strong></li><li class="sep"><h4>Sus propias palabras</h4></li><li><label>Inter&eacute;ses</label><strong>No especificado</strong></li><li><label>Hobbies</label><strong>No especificado</strong></li><li><label>Series de TV favoritas</label><strong>No especificado</strong></li><li><label>M&uacute;sica favorita</label><strong>No especificado</strong></li><li><label>Deportes y equipos</label><strong>No especificado</strong></li><li><label>Libros favoritos</label><strong>No especificado</strong></li><li><label>Pel&iacute;culas favoritas</label><strong>No especificado</strong></li><li><label>Comida favor&iacute;ta</label><strong>No especificado</strong></li><li><label>Sus heroes son</label><strong>No especificado</strong></li></ul><div class="clear"></div>

</div></div>
<div style="clear:both"></div>